{% set name = "aerobulk-python" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7275a6a7df518d9333e6e88aa0f0e33da1b71a403e0a3b7614864b300d935b5


build:
  number: 0
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - setuptools-scm
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - aerobulk.mod_aerobulk_wrap
  requires:
    - pip
  commands:
    - pip check
    - python -c "import aerobulk; assert aerobulk.__version__ == '{{ version }}', aerobulk.__version__"

about:
  home: https://github.com/xgcm/aerobulk-python
  summary: A python wrapper for the aerobulk air-sea flux fortran code
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbusecke
    - rabernat
