{% set name = "aerobulk-python" %}
{% set version = "0.4.2" %}
{% set hash = "5f89065a6dce7dff3d3f4213d10ae98185e04e3a7c74b1654e90a43e383cc31c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}



build:
  number: 0
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ stdlib("c") }}    # [win]
  host:
    - setuptools-scm
    - python
    - pip
    - numpy
  run:
    - xarray
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - aerobulk
  requires:
    - pip
  commands:
    - pip check
    - python -c "import aerobulk; assert aerobulk.__version__ == '{{ version }}', aerobulk.__version__"

about:
  home: https://github.com/xgcm/aerobulk-python
  summary: A python wrapper for the aerobulk air-sea flux fortran code
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbusecke
    - rabernat
