{% set name = "aerobulk-python" %}
{% set version = "0.4.0rc0" %}
{% set hash = "029be321ee1c52b6a7d431f58e680cab971f2b7c4f8d7bb8c8aedbe61c95a92c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}



build:
  number: 1
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - setuptools-scm
    - python <3.12
    - pip
    - numpy
  run:
    - xarray
    - python <3.12
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - aerobulk
  requires:
    - pip
  commands:
    - pip check
    - python -c "import aerobulk; assert aerobulk.__version__ == '{{ version }}', aerobulk.__version__"

about:
  home: https://github.com/xgcm/aerobulk-python
  summary: A python wrapper for the aerobulk air-sea flux fortran code
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbusecke
    - rabernat
